### ISSUE TITLE
Can't run example: 'Can't build lexer'

### ISSUE THREAD

**Issue by juanandresgs** [8u1a/plyara#25]

**Comment by juanandresgs** [comment]
ERROR: /plyara/plyara/interp.py:267: Rule t_COMMENT redefined. Previously defined on line 252
Traceback (most recent call last):
  File "examples/corpus_stats.py", line 6, in <module>
    import plyara.interp as interp
  File "/plyara/plyara/interp.py", line 363, in <module>
    lexer = lex.lex(debug=False)
  File "/anaconda2/lib/python2.7/site-packages/ply/lex.py", line 910, in lex
    raise SyntaxError("Can't build lexer")
SyntaxError: Can't build lexer

**Comment by utkonos** [comment]
This and other fixes are in the new project here:
https://github.com/plyara/plyara
